name: Wheels

on:
  push:
    branches:
      - master

env:
  GIT_REPO: "MrBitBucket/reportlab-mirror"
  REPO_DIR: reportlab
  MACOSX_DEPLOYMENT_TARGET: "10.10"
  WHEEL_SDIR: wheelhouse
  MULTIBUILD_REV: "8882150df6529658700b66bec124dfb77eefca26"
  MULTIBUILD_DIR: multibuild
  CONFIG_PATH: .travis-config.sh
  BUILD_DEPENDS: ""
  TEST_DEPENDS: "pillow pyphen"
  RLCACHE: "manylinux/reportlab"

jobs:
  clear-cache:
    name: clear-cache
    runs-on: ubuntu-latest
    steps:
      - name: setup python for clear-cache
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: clear
        env:
          CITOOLS_USER: "${{secrets.CITOOLS_USER}}"
          CITOOLS_PASSWORD: "${{secrets.CITOOLS_PASSWORD}}"
        run: |
            python -mpip install --no-cache https://hg.reportlab.com/hg-public/rl-ci-tools/archive/tip.tar.gz -U
            python -mrl_ci_tools clear-cache "$RLCACHE"
            echo "cleared remote cache for $RLCACHE"
  build:
    needs: [clear-cache]
    name: ${{matrix.python}} ${{matrix.os-name}} ${{matrix.platform}} ${{matrix.mb-ml-ver}} ${{matrix.unicode-width}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-16.04","macos-latest"]
        python: ["3.6", "3.7", "3.8", "3.9" ]
        platform: ["x86_64", "i686"]
        unicode-width: [32]
        mb-ml-ver: ["1", "2010"]
        exclude:
          - os: "macos-latest"
            platform: "i686"
          - os: "macos-latest"
            mb-ml-ver: "1"
        include:
          - os: "macos-latest"
            os-name: "osx"
          - os: "ubuntu-16.04"
            os-name: "xenial"
    env:
      BUILD_COMMIT: HEAD
      PLAT: ${{ matrix.platform }}
      MB_PYTHON_VERSION: ${{ matrix.python }}
      TRAVIS_OS_NAME: ${{ matrix.os-name }}
      UNICODE_WIDTH: ${{ matrix.unicode-width }}
      MB_ML_VER: ${{ matrix.mb-ml-ver }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build Wheel
        env:
          CITOOLS_USER: "${{secrets.CITOOLS_USER}}"
          CITOOLS_PASSWORD: "${{secrets.CITOOLS_PASSWORD}}"
        run: |
          .github/workflows/build.sh
      # Uncomment to get SSH access for testing
      # - name: Setup tmate session
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3
  email:
    name: email
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: setup python for upload
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: email confirmation
        env:
          CITOOLS_USER: "${{secrets.CITOOLS_USER}}"
          CITOOLS_PASSWORD: "${{secrets.CITOOLS_PASSWORD}}"
        run: |
            python -mpip install --no-cache https://hg.reportlab.com/hg-public/rl-ci-tools/archive/tip.tar.gz -U
            BODY="$(python -mrl_ci_tools cache-info --subdir="$RLCACHE" '*.whl')"
            NUPLOADS=$(expr $(echo "$BODY" | wc -l) - 1)
            SUBJECT="$NUPLOADS $(basename $RLCACHE) wheels uploaded to $RLCACHE by github"
            python -mrl_ci_tools email --subject="$SUBJECT" --body="$BODY"
            echo "$SUBJECT"
            echo "$BODY"
